//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CmsTalkToCms.Client.UmbracoContentService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UmbracoCrudOperationsSoap", Namespace="http://tempuri.org/")]
    public partial class UmbracoCrudOperations : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddNewsItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewsItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteNewsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UmbracoCrudOperations() {
            this.Url = global::CmsTalkToCms.Client.Properties.Settings.Default.CmsTalkToCms_Client_UmbracoContentService_UmbracoCrudOperations;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddNewsItemsCompletedEventHandler AddNewsItemsCompleted;
        
        /// <remarks/>
        public event getNewsItemsCompletedEventHandler getNewsItemsCompleted;
        
        /// <remarks/>
        public event getNewsListCompletedEventHandler getNewsListCompleted;
        
        /// <remarks/>
        public event DeleteNewsCompletedEventHandler DeleteNewsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNewsItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddNewsItems(int parentId, string name, string image, string subheader, string text) {
            object[] results = this.Invoke("AddNewsItems", new object[] {
                        parentId,
                        name,
                        image,
                        subheader,
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewsItemsAsync(int parentId, string name, string image, string subheader, string text) {
            this.AddNewsItemsAsync(parentId, name, image, subheader, text, null);
        }
        
        /// <remarks/>
        public void AddNewsItemsAsync(int parentId, string name, string image, string subheader, string text, object userState) {
            if ((this.AddNewsItemsOperationCompleted == null)) {
                this.AddNewsItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewsItemsOperationCompleted);
            }
            this.InvokeAsync("AddNewsItems", new object[] {
                        parentId,
                        name,
                        image,
                        subheader,
                        text}, this.AddNewsItemsOperationCompleted, userState);
        }
        
        private void OnAddNewsItemsOperationCompleted(object arg) {
            if ((this.AddNewsItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewsItemsCompleted(this, new AddNewsItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNewsItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public News getNewsItems(int id) {
            object[] results = this.Invoke("getNewsItems", new object[] {
                        id});
            return ((News)(results[0]));
        }
        
        /// <remarks/>
        public void getNewsItemsAsync(int id) {
            this.getNewsItemsAsync(id, null);
        }
        
        /// <remarks/>
        public void getNewsItemsAsync(int id, object userState) {
            if ((this.getNewsItemsOperationCompleted == null)) {
                this.getNewsItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewsItemsOperationCompleted);
            }
            this.InvokeAsync("getNewsItems", new object[] {
                        id}, this.getNewsItemsOperationCompleted, userState);
        }
        
        private void OngetNewsItemsOperationCompleted(object arg) {
            if ((this.getNewsItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewsItemsCompleted(this, new getNewsItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNewsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public News[] getNewsList(int id) {
            object[] results = this.Invoke("getNewsList", new object[] {
                        id});
            return ((News[])(results[0]));
        }
        
        /// <remarks/>
        public void getNewsListAsync(int id) {
            this.getNewsListAsync(id, null);
        }
        
        /// <remarks/>
        public void getNewsListAsync(int id, object userState) {
            if ((this.getNewsListOperationCompleted == null)) {
                this.getNewsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewsListOperationCompleted);
            }
            this.InvokeAsync("getNewsList", new object[] {
                        id}, this.getNewsListOperationCompleted, userState);
        }
        
        private void OngetNewsListOperationCompleted(object arg) {
            if ((this.getNewsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewsListCompleted(this, new getNewsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteNews", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteNews(int id) {
            object[] results = this.Invoke("DeleteNews", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteNewsAsync(int id) {
            this.DeleteNewsAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteNewsAsync(int id, object userState) {
            if ((this.DeleteNewsOperationCompleted == null)) {
                this.DeleteNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteNewsOperationCompleted);
            }
            this.InvokeAsync("DeleteNews", new object[] {
                        id}, this.DeleteNewsOperationCompleted, userState);
        }
        
        private void OnDeleteNewsOperationCompleted(object arg) {
            if ((this.DeleteNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteNewsCompleted(this, new DeleteNewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class News {
        
        private string bodyTextField;
        
        private string subheaderField;
        
        private string imageField;
        
        /// <remarks/>
        public string bodyText {
            get {
                return this.bodyTextField;
            }
            set {
                this.bodyTextField = value;
            }
        }
        
        /// <remarks/>
        public string subheader {
            get {
                return this.subheaderField;
            }
            set {
                this.subheaderField = value;
            }
        }
        
        /// <remarks/>
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddNewsItemsCompletedEventHandler(object sender, AddNewsItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewsItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewsItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getNewsItemsCompletedEventHandler(object sender, getNewsItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewsItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewsItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public News Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((News)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getNewsListCompletedEventHandler(object sender, getNewsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public News[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((News[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DeleteNewsCompletedEventHandler(object sender, DeleteNewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591